---
- name: Create custom job config file
  copy:
    src: "{{role_path}}/files/scm_seed_job_config.xml"
    dest: "{{role_path}}/files/custom_job_{{jenkins_job_var.name}}.xml"
    owner: jenkins
    group: jenkins
    mode: '0644'

- name: update repo path in custom_job_{{jenkins_job_var.name}}.xml
  xml:
    path: "{{role_path}}/files/custom_job_{{jenkins_job_var.name}}.xml"
    xpath: /flow-definition/definition/scm/userRemoteConfigs/hudson.plugins.git.UserRemoteConfig/url
    value: "{{jenkins_job_var.repo}}"

- name: update branch name in custom_job_{{jenkins_job_var.name}}.xml
  xml:
    path: "{{role_path}}/files/custom_job_{{jenkins_job_var.name}}.xml"
    xpath: /flow-definition/definition/scm/branches/hudson.plugins.git.BranchSpec/name
    value: "{{jenkins_job_var.branch}}"

- name: Create Custom job in Jenkins
  jenkins_job:
    config: "{{ lookup('file', 'custom_job_{{jenkins_job_var.name}}.xml') }}"
    name: "Custom_Job__{{jenkins_job_var.name}}"
    password: jenkins12
    url: "http://{{ansible_host}}:8080"
    user: jenkins
  register: add_seed_job_result
  retries: 5
  delay: 10
  until: add_seed_job_result is not failed

- name: Remove temporary custom job config file
  file:
    path: "{{role_path}}/files/custom_job_{{jenkins_job_var.name}}.xml"
    state: absent
