---
- name: Prepare Server Environment 
  include_tasks: prepare_env.yml

- name: Install Jenkins Server
  include_tasks: jenkins_install.yml

- name: unlock and add admin user and complete setup Wizard
  include_tasks: unlock_admin_complete_setup.yml

- name: Install Required Plugins
  include_tasks: plugins_install.yml

- name: Create User Defined Jobs
  include_tasks: create_custom_job_outer_loop.yml
