---
- name: Intall Jenkins Server
  include_tasks: jenkins_install.yml

- name: unlock and add admin user and complete setup Wizard
  include_tasks: unlock_admin_complete_setup.yml

- name: Install reqested plugins
  include_tasks: install_plugins.yml


