---
- name: init password jenkin
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  changed_when: false
  register: jenkin_admin_pwd_result

- name: save default admin password for further use
  set_fact:
    adminpwd: "{{jenkin_admin_pwd_result.stdout}}"


- name: install plugin
  jenkins_plugin:
    name: "{{ item }}"
    state: latest
    url_username: admin
    url_password: "{{ adminpwd }}"
  register: install_plugin_result
  retries: 5
  delay: 1
  until: install_plugin_result is not failed
  with_items: "{{ jenkins_plugins }}"

- name: Restart Jenkin Service After Plugin Installation
  service:
    name: jenkins
    state: restarted  
