---
jenkins_plugins: ['script-security', 'command-launcher','configuration-as-code','configuration-as-code-support','github','github-oauth','workflow-aggregator','dashboard-view','build-pipeline-plugin',test-results-analyzer','blueocean']
jenkins_admin_user_pass: "jenkins12"
remove_jenkins_plugins: []
JENKINS_HOME: /var/lib/jenkins
